---
- name: Ensure Explorer includes the file extension in file names.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: Ensure Right-click Context Menu enabled.
  ansible.windows.win_regedit:
    path: >
      HKCU:\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32
    data: ""
    type: none
